### ISSUE TITLE
"Migrating Relations" fails creating link table with directus_files

### ISSUE THREAD

**Issue by dwene** [directus-community/migration-tool#34] opened 2021-07-07 20:39 UTC
The migration tool seems to be failing when trying to create a many-to-many link table with `directus_files`

```
➜ node index.js
✨ Migrating https://cms.energyadvisors.com (v8) to https://directus.energyadvisors.com (v9)...
  ❯ Migrating Schema
    ✔ Downloading Schema
    ✔ Creating Collections
    ✖ Migrating Relations
      → Request failed with status code 500
    Migration Files
    Migrating Users
    Migrating Data
Error: Request failed with status code 500
    at createError (/Users/Derek/src/migration-tool/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/Derek/src/migration-tool/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/Derek/src/migration-tool/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: {
    url: '/relations',
    method: 'post',
    data: '{"meta":{"many_collection":"home_page_case_history_directus_files","many_field":"directus_files_id","many_primary":"id","one_collection":"directus_files","one_field":"home_page","one_primary":"id","junction_field":"home_page_id"},"field":"directus_files_id","collection":"home_page_case_history_directus_files","related_collection":"directus_files","schema":null}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json;charset=utf-8',
      Authorization: 'Bearer 81sG3K0mSKBKiMOrZJKF',
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 363
    },
```

I turned on DEBUG logs in my v9 directus and this is the error it's showing.

```
alter table `home_page_case_history_directus_files` add constraint `home_page_case_history_directus_files_directus_files_id_foreign` foreign key (`directus_files_id`) references `directus_files` (`id`) - ER_CANT_CREATE_TABLE: Can't create table `directus`.`home_page_case_history_directus_files` (errno: 150 "Foreign key constraint is incorrectly formed")
--
Wed, Jul 7 2021 3:27:32 pm | Error: ER_CANT_CREATE_TABLE: Can't create table `directus`.`home_page_case_history_directus_files` (errno: 150 "Foreign key constraint is incorrectly formed")
Wed, Jul 7 2021 3:27:32 pm | at Query.Sequence._packetToError (/directus/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
Wed, Jul 7 2021 3:27:32 pm | at Query.ErrorPacket (/directus/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
Wed, Jul 7 2021 3:27:32 pm | at Protocol._parsePacket (/directus/node_modules/mysql/lib/protocol/Protocol.js:291:23)
Wed, Jul 7 2021 3:27:32 pm | at Parser._parsePacket (/directus/node_modules/mysql/lib/protocol/Parser.js:433:10)
Wed, Jul 7 2021 3:27:32 pm | at Parser.write (/directus/node_modules/mysql/lib/protocol/Parser.js:43:10)
Wed, Jul 7 2021 3:27:32 pm | at Protocol.write (/directus/node_modules/mysql/lib/protocol/Protocol.js:38:16)
Wed, Jul 7 2021 3:27:32 pm | at Socket.<anonymous> (/directus/node_modules/mysql/lib/Connection.js:88:28)
Wed, Jul 7 2021 3:27:32 pm | at Socket.<anonymous> (/directus/node_modules/mysql/lib/Connection.js:526:10)
Wed, Jul 7 2021 3:27:32 pm | at Socket.emit (node:events:394:28)
Wed, Jul 7 2021 3:27:32 pm | at addChunk (node:internal/streams/readable:312:12)
```

![image](https://user-images.githubusercontent.com/12628251/124825372-257cd500-df39-11eb-909c-e104c0eaf1b3.png)

There's quite a few images in this link table. Any suggestions on how I can work with this?

Directus 9 version: 9.0.0-RC-83 using latest MariaDB
Directus 8 version: 8.8.1 and using Mysql 8

**Comment by rijkvanzanten** [comment] 2021-07-12 12:59
Seems to be a duplicate of https://github.com/directus-community/migration-tool/issues/31

**Closed** 2021-08-04 13:50 UTC
