### ISSUE TITLE
Repeater options are lost during migration

### ISSUE THREAD

**Issue by bywo** [directus-community/migration-tool#22] opened 2021-04-14 03:40 UTC
After migration, the JSON content for the field is still there, but the interface/options for the repeater field are missing, so the UI renders each item as "Empty Item".

v8
<img width="605" alt="Screen Shot 2021-04-13 at 8 38 38 PM" src="https://user-images.githubusercontent.com/1434481/114651139-3dc1b880-9c98-11eb-8991-679b60713c6f.png">
<img width="713" alt="Screen Shot 2021-04-13 at 8 37 05 PM" src="https://user-images.githubusercontent.com/1434481/114651026-10750a80-9c98-11eb-9707-4678a311810e.png">

v9
<img width="821" alt="Screen Shot 2021-04-13 at 8 38 14 PM" src="https://user-images.githubusercontent.com/1434481/114651099-2f739c80-9c98-11eb-8732-d6a2012354f6.png">
<img width="620" alt="Screen Shot 2021-04-13 at 8 37 14 PM" src="https://user-images.githubusercontent.com/1434481/114651054-179c1880-9c98-11eb-84a3-7221b866eedb.png">

**Comment by rijkvanzanten** [comment] 2021-04-14 14:33
Duplicate of #20

**Closed by rijkvanzanten** 2021-04-14 14:33 UTC
