### ISSUE TITLE
Error during migration of collection - POST -> 500

### ISSUE THREAD

**Issue by joergwirsig** [directus-community/migration-tool#4] opened 2021-03-16 13:33 UTC
The following request during migration returned a 500 

```
config: {
    url: '/collections',
    method: 'post',
    data: '{"collection":"campaign","meta":{"note":null,"hidden":false,"singleton":false,"translations":null,"sort_field":null},"schema":{},"fields":[{"field":"id","type":"integer","meta":{"note":"","interface":null,"translation":null,"readonly":false,"hidden":true,"width":"full"},"schema":{"has_auto_increment":true,"default_value":null,"is_primary_key":true,"is_nullable":false,"max_length":"10","numeric_precision":"10","numeric_scale":null}},{"field":"status","type":"string","meta":{"note":"","interface":"dropdown","translation":null,"readonly":false,"hidden":false,"width":"full"},"schema":{"has_auto_increment":false,"default_value":"draft","is_primary_key":false,"is_nullable":false,"max_length":"20","numeric_precision":"20","numeric_scale":null}},{"field":"owner","type":"uuid","meta":{"note":"","interface":"user","translation":null,"readonly":true,"hidden":true,"width":"full","special":["user-created"]},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":"10","numeric_precision":"10","numeric_scale":null}},{"field":"modified_by","type":"uuid","meta":{"note":"","interface":"user","translation":null,"readonly":true,"hidden":true,"width":"full","special":["user-updated"]},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":"10","numeric_precision":"10","numeric_scale":null}},{"field":"modified_on","type":"timestamp","meta":{"note":"","interface":"datetime","translation":null,"readonly":true,"hidden":true,"width":"full","special":["date-updated"]},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":null,"numeric_precision":null,"numeric_scale":null}},{"field":"start_date","type":"dateTime","meta":{"note":"","interface":"datetime","translation":null,"readonly":false,"hidden":false,"width":"full"},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":false,"max_length":null,"numeric_precision":null,"numeric_scale":null}},{"field":"end_date","type":"dateTime","meta":{"note":"","interface":"datetime","translation":null,"readonly":false,"hidden":false,"width":"full"},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":false,"max_length":null,"numeric_precision":null,"numeric_scale":null}},{"field":"internal_name","type":"string","meta":{"note":"Name for internal usage only","interface":"text-input","translation":null,"readonly":false,"hidden":false,"width":"full"},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":"200","numeric_precision":"200","numeric_scale":null}},{"field":"content_items","type":"alias","meta":{"note":"List of Content Items - linked to campaign - usually edited in content item directly.","interface":"one-to-many","translation":null,"readonly":false,"hidden":false,"width":"full"}},{"field":"translations","type":"integer","meta":{"note":null,"interface":"translations","translation":null,"readonly":false,"hidden":false,"width":"full"},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":null,"numeric_precision":null,"numeric_scale":null}}]}',`

Error in lokal server - which is recieving cms instance was 
`14:17:19 ­ƒÜ¿ table[field.type] is not a function
TypeError: table[field.type] is not a function
    at FieldsService.addColumnToTable (C:\Projekte\XYZ\local-XYZ-cms\XYZ-cms\node_modules\directus\dist\services\fields.js:314:39)
    at TableBuilder._fn (C:\Projekte\XYZ\local-XYZ-cms\XYZ-cms\node_modules\directus\dist\services\collections.js:90:43)
    at TableBuilder.toSQL (C:\Projekte\XYZ\local-XYZ-cms\XYZ-cms\node_modules\knex\lib\schema\tablebuilder.js:44:14)
    at SchemaCompiler_MySQL.createTable (C:\Projekte\XYZ\local-XYZ-cms\XYZ-cms\node_modules\knex\lib\schema\compiler.js:101:25)
    at SchemaCompiler_MySQL.toSQL (C:\Projekte\XYZ\local-XYZ-cms\XYZ-cms\node_modules\knex\lib\schema\compiler.js:63:26)
    at SchemaBuilder.toSQL (C:\Projekte\XYZ\local-XYZ-cms\XYZ-cms\node_modules\knex\lib\schema\builder.js:35:45)
    at ensureConnectionCallback (C:\Projekte\XYZ\local-XYZ-cms\XYZ-cms\node_modules\knex\lib\execution\internal\ensure-connection-callback.js:4:30)
    at Runner.ensureConnection (C:\Projekte\XYZ\local-XYZ-cms\XYZ-cms\node_modules\knex\lib\execution\runner.js:272:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Runner.run (C:\Projekte\XYZ\local-XYZ-cms\XYZ-cms\node_modules\knex\lib\execution\runner.js:30:19)`

Table Schema of DB Table to be migrated
`-- --------------------------------------------------------
-- Host:                         [fcfc::1:1c60:12ff:fe4b:f502]
-- Server Version:               5.7.30 - MySQL Community Server (GPL)
-- Server Betriebssystem:        Linux
-- HeidiSQL Version:             11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Exportiere Datenbank Struktur für directus
CREATE DATABASE IF NOT EXISTS `directus` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `directus`;

-- Exportiere Struktur von Tabelle directus.campaign
CREATE TABLE IF NOT EXISTS `campaign` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft',
  `owner` int(10) unsigned DEFAULT NULL,
  `modified_by` int(10) unsigned DEFAULT NULL,
  `modified_on` datetime DEFAULT NULL,
  `start_date` datetime NOT NULL,
  `end_date` datetime NOT NULL,
  `internal_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Name for internal usage only',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Exportiere Daten aus Tabelle directus.campaign: ~4 rows (ungefähr)
/*!40000 ALTER TABLE `campaign` DISABLE KEYS */;
INSERT INTO `campaign` (`id`, `status`, `owner`, `modified_by`, `modified_on`, `start_date`, `end_date`, `internal_name`) VALUES
	(1, 'deleted', 1, 4, '2020-06-29 11:25:11', '2020-06-15 00:00:00', '2020-08-31 00:00:00', NULL),
	(2, 'published', 4, 13, '2021-01-07 10:33:10', '2020-07-15 00:01:00', '2020-12-10 00:59:00', 'Campaign_expired'),
	(3, 'published', 3, 1, '2021-02-23 10:12:45', '2020-12-09 00:00:00', '2021-02-28 20:20:00', 'Xmas'),
	(4, 'published', 8, 8, '2021-02-25 14:54:36', '2021-03-01 00:23:00', '2021-04-29 23:59:00', 'Eastern');
/*!40000 ALTER TABLE `campaign` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;

```

Please let me know if you need any further information.

**Comment by prasadbandur** [comment] 2021-03-17 11:48
Same issue faced by me too. 
Request sent: ```
config: {
    url: '/collections',
    method: 'post',
    data: '{"collection":"auth","meta":{"note":null,"hidden":true,"singleton":false,"translations":null,"sort_field":null},"schema":{},"fields":[{"field":"id","type":"integer","meta":{"note":"","interface":null,"translation":null,"readonly":false,"hidden":true,"width":"full"},"schema":{"has_auto_increment":true,"default_value":null,"is_primary_key":true,"is_nullable":false,"max_length":"10","numeric_precision":"10","numeric_scale":null}},{"field":"owner","type":"uuid","meta":{"note":"","interface":"user","translation":null,"readonly":true,"hidden":true,"width":"full","special":["user-created"]},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":"10","numeric_precision":"10","numeric_scale":null}},{"field":"created_on","type":"timestamp","meta":{"note":"","interface":"datetime","translation":null,"readonly":true,"hidden":true,"width":"full","special":["date-created"]},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":null,"numeric_precision":null,"numeric_scale":null}},{"field":"type","type":"string","meta":{"note":"","interface":"dropdown","translation":null,"readonly":false,"hidden":false,"width":"half"},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":false,"max_length":"100","numeric_precision":"100","numeric_scale":null}},{"field":"booking","type":"integer","meta":{"note":"","interface":"many-to-one","translation":null,"readonly":false,"hidden":false,"width":"half","special":["m2o"]},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":"10","numeric_precision":"10","numeric_scale":null}},{"field":"search","type":"integer","meta":{"note":"","interface":"many-to-one","translation":null,"readonly":false,"hidden":false,"width":"full","special":["m2o"]},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":"10","numeric_precision":"10","numeric_scale":null}},{"field":"static","type":"alias","meta":{"note":null,"interface":"one-to-many","translation":null,"readonly":false,"hidden":false,"width":"full"}},{"field":"token","type":"alias","meta":{"note":null,"interface":"one-to-many","translation":null,"readonly":false,"hidden":false,"width":"full"}}]}',
```

Response:
```
response: {
    status: 500,
    statusText: 'Internal Server Error',
    headers: {
      'x-powered-by': 'Directus',
      vary: 'Origin',
      'access-control-allow-credentials': 'true',
      'access-control-expose-headers': 'Content-Range',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '108',
      etag: 'W/"6c-mFHqbPPqXAormIgoR5mQNoYeOXQ"',
      date: 'Wed, 17 Mar 2021 11:24:16 GMT',
      connection: 'close'
    },
```

**Comment by moekify** [comment] 2021-03-20 13:52
Can report the same error :) 

```| 13:47:35 🚨 table[field.type] is not a function
directus_1  | TypeError: table[field.type] is not a function
directus_1  |     at FieldsService.addColumnToTable (/directus/node_modules/directus/dist/services/fields.js:314:39)
directus_1  |     at TableBuilder._fn (/directus/node_modules/directus/dist/services/collections.js:90:43)
directus_1  |     at TableBuilder.toSQL (/directus/node_modules/knex/lib/schema/tablebuilder.js:44:14)
directus_1  |     at SchemaCompiler_PG.createTable (/directus/node_modules/knex/lib/schema/compiler.js:101:25)
directus_1  |     at SchemaCompiler_PG.toSQL (/directus/node_modules/knex/lib/schema/compiler.js:63:26)
directus_1  |     at SchemaBuilder.toSQL (/directus/node_modules/knex/lib/schema/builder.js:35:45)
directus_1  |     at ensureConnectionCallback (/directus/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
directus_1  |     at Runner.ensureConnection (/directus/node_modules/knex/lib/execution/runner.js:272:20)
directus_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
directus_1  |     at async Runner.run (/directus/node_modules/knex/lib/execution/runner.js:30:19)
directus_1  | 13:47:35 ✨ request errored POST 500 /collections 58ms```

**Comment by rijkvanzanten** [comment] 2021-03-21 13:59
I think it's caused by the fact that Directus fails to ignore `type: 'alias'` as a "non-existing column" type 🙂

**Comment by rijkvanzanten** [comment] 2021-03-21 14:28
This should be fixed starting in RC.52 👍🏻

**Closed** 2021-03-21 14:27 UTC

**Comment by moekify** [comment] 2021-03-21 14:29
@rijkvanzanten Thanks for the quick fix here! Very much appreciated <3
