### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by countnoobula** [directus-community/migration-tool#29] opened 2021-05-19 10:42 UTC
Hi all, 

We're trying to migrate a v8 stack of Directus to v9. 
Both run in Docker, and we're attempting to migrate from MySQL to PgSQL. 
Unfortunately, we seem to have trouble with files, and I was hoping someone may be able to shed some light please?

```
 ❯ Migration Files
    ✔ Getting File Count
    ❯ Uploading Files
      ✖ Uploading files 1—100
        → Cannot read property 'split' of undefined
        Uploading files 101—200
        Uploading files 201—300
        Uploading files 301—400
        Uploading files 401—500
    Migrating Users
    Migrating Data
TypeError: Cannot read property 'split' of undefined
```

**Comment by hakan-erdem-temiz** [comment] 2021-06-08 13:13
There is no attribute for the "GET /:project/files" endpoint as the asset_url. Maybe the "full_url" attribute can be used instead of asset_url. (https://v8.docs.directus.io/api/files.html#list-the-files)

`  "data": {
    "full_url": "https://demo.directus.io/uploads/thumper/originals/a88c3b72-ac58-5436-a4ec-b2858531333a.jpg",
    "url": "/uploads/thumper/originals/a88c3b72-ac58-5436-a4ec-b2858531333a.jpg",
    "thumbnails": [
      {
        "url": "https://demo.directus.io/thumper/assets/pnw7s9lqy68048g0?key=directus-small-crop",
        "relative_url": "/thumper/assets/pnw7s9lqy68048g0?key=directus-small-crop",
        "dimension": "64x64",
        "width": 64,
        "height": 64
      },
      { ... },
      { ... }
    ],
    "embed": null
  }`

**Comment by hakan-erdem-temiz** [comment] 2021-06-10 08:37
There is no asset_url but you can use full_url. Also you need to change url. 

`	const savedFile = await apiV9.post("/files/import", {
		url: fileRecord.data.full_url,
		data: {
			filename_download: fileRecord.filename_download,
			title: fileRecord.title,
			description: fileRecord.description,
		},
	});`

**Comment by rijkvanzanten** [comment] 2021-08-17 13:31
Duplicate of https://github.com/directus-community/migration-tool/issues/16

**Closed by rijkvanzanten** 2021-08-17 13:31 UTC
