### ISSUE TITLE
Unexpected error when migrating colection

### ISSUE THREAD

**Issue by lluishi93** [directus-community/migration-tool#6] opened 2021-03-24 16:01 UTC
We're trying to migrate v8 to v9, and we get an internal server error with this request, generated by the migration tool:

```json
{
    "collection": "circle_badges_component",
    "meta": {
        "note": null,
        "hidden": false,
        "singleton": false,
        "translations": null,
        "sort_field": null
    },
    "schema": {},
    "fields": [
        {
            "field": "id",
            "type": "integer",
            "meta": {
                "note": "",
                "interface": null,
                "translation": null,
                "readonly": false,
                "hidden": true,
                "width": "full"
            },
            "schema": {
                "has_auto_increment": true,
                "default_value": null,
                "is_primary_key": true,
                "is_nullable": false,
                "max_length": "10",
                "numeric_precision": "10",
                "numeric_scale": null
            }
        },
        {
            "field": "status",
            "type": "string",
            "meta": {
                "note": "",
                "interface": "dropdown",
                "translation": null,
                "readonly": false,
                "hidden": false,
                "width": "full"
            },
            "schema": {
                "has_auto_increment": false,
                "default_value": "draft",
                "is_primary_key": false,
                "is_nullable": false,
                "max_length": "20",
                "numeric_precision": "20",
                "numeric_scale": null
            }
        },
        {
            "field": "owner",
            "type": "uuid",
            "meta": {
                "note": "",
                "interface": "user",
                "translation": null,
                "readonly": true,
                "hidden": true,
                "width": "full",
                "special": [
                    "user-created"
                ]
            },
            "schema": {
                "has_auto_increment": false,
                "default_value": null,
                "is_primary_key": false,
                "is_nullable": true,
                "max_length": "10",
                "numeric_precision": "10",
                "numeric_scale": null
            }
        },
        {
            "field": "created_on",
            "type": "timestamp",
            "meta": {
                "note": "",
                "interface": "datetime",
                "translation": null,
                "readonly": true,
                "hidden": true,
                "width": "full",
                "special": [
                    "date-created"
                ]
            },
            "schema": {
                "has_auto_increment": false,
                "default_value": null,
                "is_primary_key": false,
                "is_nullable": true,
                "max_length": null,
                "numeric_precision": null,
                "numeric_scale": null
            }
        },
        {
            "field": "name",
            "type": "string",
            "meta": {
                "note": "",
                "interface": "text-input",
                "translation": null,
                "readonly": false,
                "hidden": false,
                "width": "half"
            },
            "schema": {
                "has_auto_increment": false,
                "default_value": null,
                "is_primary_key": false,
                "is_nullable": true,
                "max_length": "200",
                "numeric_precision": "200",
                "numeric_scale": null
            }
        },
        {
            "field": "order",
            "type": "integer",
            "meta": {
                "note": "",
                "interface": "numeric",
                "translation": null,
                "readonly": false,
                "hidden": false,
                "width": "full"
            },
            "schema": {
                "has_auto_increment": false,
                "default_value": null,
                "is_primary_key": false,
                "is_nullable": true,
                "max_length": "10",
                "numeric_precision": "10",
                "numeric_scale": null
            }
        },
        {
            "field": "margin_top_desktop",
            "type": "integer",
            "meta": {
                "note": "Number of pixels for the top margin of the module (desktop)",
                "interface": "numeric",
                "translation": null,
                "readonly": false,
                "hidden": false,
                "width": "full"
            },
            "schema": {
                "has_auto_increment": false,
                "default_value": null,
                "is_primary_key": false,
                "is_nullable": true,
                "max_length": "10",
                "numeric_precision": "10",
                "numeric_scale": null
            }
        },
        {
            "field": "margin_bottom_desktop",
            "type": "integer",
            "meta": {
                "note": "Number of pixels for the bottom margin of the module (desktop)",
                "interface": "numeric",
                "translation": null,
                "readonly": false,
                "hidden": false,
                "width": "full"
            },
            "schema": {
                "has_auto_increment": false,
                "default_value": null,
                "is_primary_key": false,
                "is_nullable": true,
                "max_length": "10",
                "numeric_precision": "10",
                "numeric_scale": null
            }
        },
        {
            "field": "margin_top_mobile",
            "type": "integer",
            "meta": {
                "note": "Number of pixels for the top margin of the module (mobile)",
                "interface": "numeric",
                "translation": null,
                "readonly": false,
                "hidden": false,
                "width": "full"
            },
            "schema": {
                "has_auto_increment": false,
                "default_value": null,
                "is_primary_key": false,
                "is_nullable": true,
                "max_length": "10",
                "numeric_precision": "10",
                "numeric_scale": null
            }
        },
        {
            "field": "margin_bottom_mobile",
            "type": "integer",
            "meta": {
                "note": "Number of pixels for the bottom margin of the module (mobile)",
                "interface": "numeric",
                "translation": null,
                "readonly": false,
                "hidden": false,
                "width": "full"
            },
            "schema": {
                "has_auto_increment": false,
                "default_value": null,
                "is_primary_key": false,
                "is_nullable": true,
                "max_length": "10",
                "numeric_precision": "10",
                "numeric_scale": null
            }
        },
        {
            "field": "device",
            "type": "string",
            "meta": {
                "note": "The device where the module will appear",
                "interface": "text-input",
                "translation": null,
                "readonly": false,
                "hidden": false,
                "width": "full"
            },
            "schema": {
                "has_auto_increment": false,
                "default_value": "both",
                "is_primary_key": false,
                "is_nullable": true,
                "max_length": "100",
                "numeric_precision": "100",
                "numeric_scale": null
            }
        },
        {
            "field": "date_programations",
            "type": "text",
            "meta": {
                "note": "When the banner will appear and disappear by site (UTC zone time)",
                "interface": "repeater",
                "translation": null,
                "readonly": false,
                "hidden": false,
                "width": "full",
                "special": [
                    "json"
                ]
            },
            "schema": {
                "has_auto_increment": false,
                "default_value": null,
                "is_primary_key": false,
                "is_nullable": true,
                "max_length": "65535",
                "numeric_precision": "65535",
                "numeric_scale": null
            }
        },
        {
            "field": "typography",
            "type": "string",
            "meta": {
                "note": "Choose between standard component typography (openSans, Agaramond...) or Montserrat typography",
                "interface": "radio-buttons",
                "translation": null,
                "readonly": false,
                "hidden": false,
                "width": "full"
            },
            "schema": {
                "has_auto_increment": false,
                "default_value": "standard",
                "is_primary_key": false,
                "is_nullable": true,
                "max_length": "100",
                "numeric_precision": "100",
                "numeric_scale": null
            }
        },
        {
            "field": "platform",
            "type": "string",
            "meta": {
                "note": "",
                "interface": "text-input",
                "translation": null,
                "readonly": false,
                "hidden": false,
                "width": "full"
            },
            "schema": {
                "has_auto_increment": false,
                "default_value": "both",
                "is_primary_key": false,
                "is_nullable": true,
                "max_length": "10",
                "numeric_precision": "10",
                "numeric_scale": null
            }
        },
        {
            "field": "circle_badges",
            "type": "alias",
            "meta": {
                "note": "include the circle badges. max.9 categories to be contributed",
                "interface": "many-to-many",
                "translation": null,
                "readonly": false,
                "hidden": false,
                "width": "full"
            }
        }
    ]
}
```

and this is the error that we get
![image](https://user-images.githubusercontent.com/14786440/112342266-5efb3e80-8cc2-11eb-8a1e-20d5366401ff.png)

**Comment by rijkvanzanten** [comment] 2021-03-24 16:02
Duplicate of https://github.com/directus-community/migration-tool/issues/4

**Closed by rijkvanzanten** 2021-03-24 16:02 UTC
